name: "Get Terraform outputs"
inputs:
  terraform-state-bucket-name:
    description: "The name of the Terraform state S3 bucket"
    required: true
  terraform-state-lock-table-name:
    description: "The name of the Terraform state-lock DynamoDB table"
    required: true
  terraform-directory:
    description: "The directory where the Terraform command will be executed"
    required: true
outputs:
  s3-bucket-name:
    description: "The name of the S3 bucket hosting the React app"
    value: ${{ steps.get-terraform-outputs.outputs.s3-bucket-name }}
  s3-bucket-role-arn:
    description: "The ARN of the IAM role that can make changes to files in the S3 bucket"
    value: ${{ steps.get-terraform-outputs.outputs.s3-bucket-role-arn }}
runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Initialise Terraform
      shell: bash
      run: |
        terraform init \
          -backend-config="bucket=${{ inputs.terraform-state-bucket-name }}" \
          -backend-config="dynamodb_table=${{ inputs.terraform-state-lock-table-name }}" \
      working-directory: ${{ inputs.terraform-directory }}
    - name: Get Terraform outputs
      id: get-terraform-outputs
      working-directory: ${{ inputs.terraform-directory }}
      shell: bash
      run: |
        S3_BUCKET_NAME=$(terraform output -raw S3_BUCKET_NAME)
        S3_BUCKET_ROLE_ARN=$(terraform output -raw S3_BUCKET_ROLE_ARN)
        echo "s3-bucket-name=$S3_BUCKET_NAME" >> $GITHUB_OUTPUT
        echo "s3-bucket-role-arn=$S3_BUCKET_ROLE_ARN" >> $GITHUB_OUTPUT
