name: "Get Terraform outputs"
inputs:
  terraform-state-bucket-name:
    description: "The name of the Terraform state S3 bucket"
    required: true
  terraform-state-lock-table-name:
    description: "The name of the Terraform state-lock DynamoDB table"
    required: true
  terraform-directory:
    description: "The directory where the Terraform command will be executed"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Initialise Terraform
      shell: bash
      run: |
        terraform init \
          -backend-config="bucket=${{ inputs.terraform-state-bucket-name }}" \
          -backend-config="dynamodb_table=${{ inputs.terraform-state-lock-table-name }}" \
      working-directory: ${{ inputs.terraform-directory }}
    - name: Get Terraform outputs
      run: terraform output
      working-directory: ${{ inputs.terraform-directory }}
      shell: bash
