name: run-terraform-command
on:
  workflow_call:
    inputs:
      terraform-command:
        required: true
        type: string
      aws-region:
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
jobs:
  run-terraform-command:
    name: Run Terraform command
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get CloudFormation stack name
        id: get-cloudformation-stack-name
        uses: ./.github/actions/get-cloudformation-stack-name
      - name: Describe CloudFormation stack
        id: describe-cloudformation-stack
        uses: ./.github/actions/describe-cloudformation-stack
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-region: ${{ inputs.aws-region }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          stack-name: ${{ steps.get-cloudformation-stack-name.outputs.stack-name }}
      - name: Run Terraform apply
        uses: ./.github/actions/configure-terraform-and-run-command
        with:
          aws-region: ${{ inputs.aws-region }}
          terraform-command: ${{ inputs.terraform-command }}
          terraform-directory: ./terraform
          terraform-execution-role-arn: ${{ steps.describe-cloudformation-stack.outputs.terraform-execution-role-arn }}
          terraform-state-bucket-name: ${{ steps.describe-cloudformation-stack.outputs.terraform-state-bucket-name }}
          terraform-state-lock-table-name: ${{ steps.describe-cloudformation-stack.outputs.terraform-state-lock-table-name }}
