name: run-terraform-apply-on-dispatch
on:
  workflow_dispatch:
jobs:
  run-terraform-apply:
    name: Run Terraform apply
    uses: ./.github/workflows/run-terraform-command.yml
    with:
      terraform-command: terraform apply -auto-approve
